### ISSUE TITLE
I made some discoveries to make FiveM run smoother while in las venturas/san fierro!

### ISSUE THREAD

**Issue by ReadyP1ayerTwo** [rjmxtechnology/SFLV-GTABelgium_FiveM-Ready#1]
it helps a LOT if you turn your distance scaling off in graphics settings. if you go to advanced graphics settings and turn off extended distance scaling, that seems to help the most out of anything. Before i turned off distance scaling, it was taking about 38-40ms to render each frame. Once i turned it off, it dropped down to as low as 6 to 12ms!

Side note: I found some invisible objects with collisions. The coordinates are X:6990.9735 Y:10056.08889 Z:10.1683

 I hope this information helps you in optimizing the map for FiveM!

![image](https://user-images.githubusercontent.com/53491846/86992781-45d05300-c170-11ea-8922-c7fa1ff1f4b5.png)

**Comment by rjmxtechnology** [comment]
Unfortunately in terms of the state of this repo this is probably as far as I intended it to go, I just uploaded it here since the topic got closed on cfx.re forums. However make no mistake, this doesn't mean I am not open to any contributions or improvements. 
If you find any fixes etc...feel free to submit a pull request. In terms of these files here what I uploaded was identical to GTABelgium's GTA-5Mods Release with the exception of the textures being resized so they would work easily in FiveM without splitting the ytd files. Nice to see this is getting some use however!!!

**Comment by ReadyP1ayerTwo** [comment]
@rjmxtechnology you should totally make mention of how much of a difference turning down extended distance scaling makes in the readme ;) i don't like the idea of leaving people behind on improvements.

**Comment by rjmxtechnology** [comment]
Where does one find that option? Just so I can clarify, would you mind posting a screenshot with a red square outline around it?

**Comment by ReadyP1ayerTwo** [comment]
@rjmxtechnology Here you go! =]
![image](https://user-images.githubusercontent.com/53491846/87141101-88795480-c270-11ea-80fd-56466e842653.png)

**Comment by rjmxtechnology** [comment]
Bit late but I added it to the readme
